[package]
name = "argsclsk"
version = "0.1.2"
edition = "2021"
license = "LGPL-3.0-or-later"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
loggerk = { git="https://github.com/hanishkvc/prgs-rustland-libs-loggerk" }

